vich_uploader:
    db_driver: orm

    mappings:
        pin_images:
            uri_prefix: /images/pins
            upload_destination: '%kernel.project_dir%/public/images/pins'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
